name: phtok
favicon: null
layout_spectrum: 0.23803389980457723
typography_spectrum: 0.42004428524523973
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.529373697238043
  lightness: 0.3530419983435422
  saturation: 0.016253271140158176
  rhythmicContrast: 0.04583894950337708
purpose: []
