name: phtok
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#05060b'
    - '#1a2053'
    - '#54629c'
    - '#39141c'
    - '#4c2261'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
